CodiTramuntana/decidim-i2cat-app

Gemfile.lock

Update devise gem due to vulnerability. 
https://github.com/CodiTramuntana/decidim-i2cat-app/network/alert/Gemfile.lock/devise/open

update devise gem

---

Gemfile
Gemfile.lock
app/assets/stylesheets/application.scss
config/schedule.rb
db/migrate/20190916065811_create_decidim_term_customizer_translation_sets.decidim_term_customizer.rb
db/migrate/20190916065812_create_decidim_term_customizer_translations.decidim_term_customizer.rb
db/migrate/20190916065813_create_decidim_term_customizer_constraints.decidim_term_customizer.rb
db/schema.rb

Hide link open data on footer.
Add term customizer

hide link open data with css and add term customizer

---

Gemfile
Gemfile.lock
db/migrate/20191231111134_add_conferences.decidim_conferences.rb
db/migrate/20191231111135_add_conference_user_roles.decidim_conferences.rb
db/migrate/20191231111136_add_conference_speakers.decidim_conferences.rb
db/migrate/20191231111137_add_conference_invites.decidim_conferences.rb
db/migrate/20191231111138_add_conference_registrations.decidim_conferences.rb
db/migrate/20191231111139_add_conferences_partner.decidim_conferences.rb
db/migrate/20191231111140_add_relation_between_speaker_and_meeting.decidim_conferences.rb
db/migrate/20191231111141_add_conference_media_link.decidim_conferences.rb
db/migrate/20191231111142_add_conference_registration_types.decidim_conferences.rb
db/migrate/20191231111143_add_reference_registration_type_to_conference_registration.decidim_conferences.rb
db/migrate/20191231111144_add_registration_type_to_conference_invite.decidim_conferences.rb
db/migrate/20191231111145_add_diploma_fields_to_conference.decidim_conferences.rb
db/migrate/20191231111146_make_price_optional_conference_registration_type.decidim_conferences.rb
db/schema.rb

Solves basecamp's: https://3.basecamp.com/4186608/buckets/12708820/todos/2286106971
Installed decidim-conferences gem.

[FIX] installed decidim-conferences

---

Gemfile
Gemfile.lock
config/environments/production.rb

For integration problems with other Decidim installations

Migrate hackovid to sidekiq

---

app/assets/stylesheets/application.scss

This PR hides the help text shown above the pages.

Hide help text

---

app/controllers/decidim/assemblies/admin/assembly_followers_controller.rb
config/locales/ca.yml
config/locales/es.yml

Correct translations and params call.
Related to https://github.com/CodiTramuntana/decidim-i2cat-app/pull/22

Followers fix

---

app/controllers/decidim/pages_controller.rb
docs/overrides.md

Now when you press the help button it redirects to a specific page which slug is '_smartcataloniachallenge_'.

Redirect help page to a specific page.

---

app/assets/stylesheets/application.scss

The menu button background color is changed to a lighter color.
**Before**
**After**

Change landing page background color

---

db/migrate/20210319075630_invalidate_all_sessions_for_deleted_users.decidim.rb
db/migrate/20210319075631_add_salt_to_decidim_forms_questionnaires.decidim_forms.rb
db/migrate/20210319075632_add_salt_to_decidim_meetings.decidim_meetings.rb
db/schema.rb

Some migrations were not installed after the last upgrde.
This PR adds those migrations that were missing.

Add pending migrations

---

config/locales/es.yml

The main key was wrong in the spanish translations file.

Fix key in spanish translations file

---

Gemfile
Gemfile.lock

Upgrade decidim-challenges to v0.0.6

---

Gemfile
Gemfile.lock

Avoid very long cards, make all cards of the same size.

Upgrade decidim-challenges to v0.0.7

---

Gemfile
Gemfile.lock

Gem update with:
- New module name
- Fix long text in solutions and problems.

Update module decidim-challenges

---

Gemfile
Gemfile.lock
app/controllers/concerns/decidim/challenges/orderable_challenges.rb
config/locales/ca.yml
config/locales/en.yml
config/locales/es.yml

- Bump decidim-challenges version.
- Add alphabetically order in challenges list.

Alphabetically order in challenges

---

db/migrate/20191231111134_add_conferences.decidim_conferences.rb
db/migrate/20191231111135_add_conference_user_roles.decidim_conferences.rb
db/migrate/20191231111136_add_conference_speakers.decidim_conferences.rb
db/migrate/20191231111137_add_conference_invites.decidim_conferences.rb
db/migrate/20191231111138_add_conference_registrations.decidim_conferences.rb
db/migrate/20191231111139_add_conferences_partner.decidim_conferences.rb
db/migrate/20191231111140_add_relation_between_speaker_and_meeting.decidim_conferences.rb
db/migrate/20191231111141_add_conference_media_link.decidim_conferences.rb
db/migrate/20191231111142_add_conference_registration_types.decidim_conferences.rb
db/migrate/20191231111143_add_reference_registration_type_to_conference_registration.decidim_conferences.rb
db/migrate/20191231111144_add_registration_type_to_conference_invite.decidim_conferences.rb
db/migrate/20191231111145_add_diploma_fields_to_conference.decidim_conferences.rb
db/migrate/20191231111146_make_price_optional_conference_registration_type.decidim_conferences.rb
db/migrate/20200929122997_index_foreign_keys_in_decidim_conferences.decidim_conferences.rb
db/migrate/20200929122998_index_foreign_keys_in_decidim_conferences_conference_invites.decidim_conferences.rb
db/migrate/20200929122999_index_foreign_keys_in_decidim_conferences_conference_registrations.decidim_conferences.rb

Re introduce migrations lost because of PR #53 .

Add mistakenly removed migrations

---

app/decorators/cells/decidim/assemblies/assembly_m_cell_decorator.rb
config/initializers/i2cat.rb
spec/system/assemblies_spec.rb

Remove custom host for tags in assemblies.

Set tags in all hosts

---

Gemfile
Gemfile.lock

- Bump decidim-challenges version to v0.0.12

Get images in Challenges cards

---

db/migrate/20220420080209_add_card_image_to_challenges.decidim_challenges.rb
db/schema.rb

Related with: https://github.com/CodiTramuntana/decidim-i2cat-app/pull/79

Add missing migration for card image in challenges

---

Gemfile
Gemfile.lock
config/locales/ca.yml
config/locales/es.yml
spec/features/remove_overrides_spec.rb

- Fix rollback transaction in Decidim 0.24
- Add missing translations with test
TODO

Fix when a file in survey has any error in format

---

README.md
app/packs/stylesheets/decidim/decidim_application.scss
app/views/decidim/shared/_custom_process_nav.html.erb
app/views/decidim/shared/_extended_navigation_bar.html.erb
app/views/decidim/shared/_normal_process_nav.html.erb
spec/system/extended_navigation_bar_spec.rb

- Changed the process nav to always show as a dropdown (like in the mobile view) for assemblies/atles.

Customize process navbar in atles assembly

---

config/application.rb
config/initializers/redirects.rb
lib/middlewares/redirect_middleware.rb
spec/system/redirect_middleware_spec.rb

Add redirect middleware to redirect from `/pages` to `/pages/que-es`

Add redirect middleware

---

Gemfile
Gemfile.lock

Update challenges module to fix error in searches challenges.
PR in challenges: https://github.com/gencat/decidim-module-challenges/pull/66

Update challenges module

---

.github/workflows/ci_app.yml
Gemfile
Gemfile.lock

Fix upload card images in challenges when the last version of module:
https://github.com/gencat/decidim-module-challenges/releases/tag/v0.3.2

Update decidim challenges version
